drivers: translate OSError to a more readable error
__main__ now prints:
ERROR: pifpaf: Unable to run command `memcached -vv -p 11212': [Errno 2] No such file or directory

which is better.